swagger: "2.0"
info:
  description: The internet controllable smiley sign
  title: Smiler
  version: 1.0.0
consumes:
  - application/com.shanaghy.smiler.v1+json
produces:
  - application/com.shanaghy.smiler.v1+json
schemes:
  - http
definitions:
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
      message:
        type: string

  FlashState:
    type: object
    required:
      - freq
    properties:
      freq:
        type: integer

paths:
  /authd:
    get:
      operationId: "GetFlashState"
      tags:
        - flash
      responses:
        200:
          description: The request was accepted successfully
          schema:
            $ref: "#/definitions/FlashState"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"
  /flash:
    get:
      operationId: "GetFlashState"
      tags:
        - flash
      responses:
        200:
          description: The request was accepted successfully
          schema:
            $ref: "#/definitions/FlashState"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"
    put:
      operationId: "SetFlashState"
      tags:
        - flash
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/FlashState"
      responses:
        204:
          description: The request was accepted successfully
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"
